# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)

# Upper bound (bytes) for one tile.  The copy is pure streaming traffic, so the
# tile is sized in bytes rather than in elements: fp16/bfloat16 get 16384
# elements (32 KiB) and fp32 gets 8192 elements (32 KiB) from the same kernel.
_TILE_BYTES = 32768


@triton.jit
def narrow_copy_kernel(
    out_ptr,
    inp_ptr,
    src_off,
    run,
    row_in,
    nseg,
    BLOCK: tl.constexpr,
    EVEN: tl.constexpr,
):
    """Row-structured narrow copy.

    A contiguous input viewed as ``[outer, dim_size * inner]`` and narrowed on
    the middle axis produces ``outer`` contiguous *runs* of ``run = length *
    inner`` elements.  Each program owns one BLOCK-sized slice of one run, so the
    address of every loaded/stored element is a single affine expression: no
    per-element integer division or modulo is needed at all.
    """
    pid = tl.program_id(0)
    row = pid // nseg
    seg = pid - row * nseg
    off = seg * BLOCK + tl.arange(0, BLOCK)
    ip = inp_ptr + (src_off + row * row_in) + off
    op = out_ptr + row * run + off
    if EVEN:
        # Full tile: no predicate, so the movers issue plain contiguous DMA.
        tl.store(op, tl.load(ip))
    else:
        m = off < run
        tl.store(op, tl.load(ip, mask=m), mask=m)


def narrow_copy(inp, dim, start, length):
    logger.debug("GEMS NARROW_COPY")
    assert (
        dim >= -inp.ndim and dim < inp.ndim
    ), f"Invalid dim: {dim} for tensor with {inp.ndim} dimensions"
    dim = dim % inp.ndim

    # Handle negative start
    if start < 0:
        start = start % inp.size(dim)

    # Clamp length to valid range
    length = min(length, inp.size(dim) - start)

    # Compute output shape
    out_shape = list(inp.shape)
    out_shape[dim] = length
    out = torch.empty(out_shape, dtype=inp.dtype, device=inp.device)

    if out.numel() == 0:
        return out

    # Make input contiguous for simpler indexing
    inp = inp.contiguous()
    dim_size = inp.size(dim)

    # Element counts of the dims after / before the narrowed dim.
    inner = 1
    for d in range(dim + 1, inp.ndim):
        inner *= inp.size(d)

    run = length * inner  # contiguous elements of one outer slice
    src_off = start * inner  # start of the first run inside a slice
    row_in = dim_size * inner  # distance between two consecutive slices
    outer = inp.numel() // row_in

    block = min(_TILE_BYTES // inp.element_size(), triton.next_power_of_2(run))
    nseg = triton.cdiv(run, block)

    narrow_copy_kernel[(outer * nseg,)](
        out,
        inp,
        src_off,
        run,
        row_in,
        nseg,
        BLOCK=block,
        EVEN=(run % block == 0),
    )

    return out


run = narrow_copy
