"""Compatibility imports for :mod:`kernelgen_server.protocol.client`."""

from .protocol.client import (
    EVALUATION_MAX_ATTEMPTS,
    EVALUATION_TRANSPORT_GRACE_SECONDS,
    OperationCancelledError,
    ServerError,
    cancel_debug_job,
    cancel_operation,
    download_debug_artifacts,
    evaluate,
    get_operator_bundle,
    get_operator_contract,
    get_debug_job,
    get_operation,
    inspect,
    operator_bundle_exists,
    preflight,
    reference,
    profile,
    status,
    submit_debug_job,
    upload_operator_bundle,
)

__all__ = [
    "EVALUATION_MAX_ATTEMPTS",
    "EVALUATION_TRANSPORT_GRACE_SECONDS",
    "OperationCancelledError",
    "ServerError",
    "cancel_debug_job",
    "cancel_operation",
    "download_debug_artifacts",
    "evaluate",
    "get_operator_bundle",
    "get_operator_contract",
    "get_debug_job",
    "get_operation",
    "inspect",
    "operator_bundle_exists",
    "preflight",
    "reference",
    "profile",
    "status",
    "submit_debug_job",
    "upload_operator_bundle",
]
