# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import dim_compress, libentry, libtuner
from flag_gems.utils import triton_lang_extension as tle
from flag_gems.utils.limits import get_dtype_max

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Copy-free single-dimension kernels.
#
# For a contiguous input and a single reduction axis d the tensor can be seen
# as a dense (O, K, I) block (O = prod(shape[:d]), K = shape[d],
# I = prod(shape[d+1:])) with unit strides, so no materialised transpose /
# contiguous copy is needed.
#
#   * I == 1  -> plain row reduction of the (O, K) matrix over its last axis.
#   * I  > 1  -> reduction over the middle axis; a (BLOCK_K, BLOCK_I) tile is a
#                contiguous run of BLOCK_K*BLOCK_I elements whenever
#                BLOCK_I == I, so the load stays fully coalesced.
#
# Min is exact in the operand dtype (it selects one of its inputs), therefore
# the accumulation is carried in the input dtype and every result is
# bit-identical to a higher precision accumulator.
# ---------------------------------------------------------------------------


@libentry()
@triton.jit
def amin_last_kernel(
    x_ptr,
    out_ptr,
    M,
    N,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    dtype = x_ptr.dtype.element_ty
    acc_type = tl.float32 if dtype is tl.bfloat16 else dtype
    pid = tl.program_id(0)
    rows = pid * BLOCK_M + tl.arange(0, BLOCK_M)
    rmask = rows < M
    acc = tl.full([BLOCK_M, BLOCK_N], float("inf"), dtype=acc_type)
    for off in range(0, N, BLOCK_N):
        cols = off + tl.arange(0, BLOCK_N)
        cmask = cols < N
        val = tl.load(
            x_ptr + rows[:, None] * N + cols[None, :],
            mask=rmask[:, None] & cmask[None, :],
            other=float("inf"),
        )
        acc = tl.minimum(acc, val.to(acc_type))
    tl.store(out_ptr + rows, tl.min(acc, axis=1).to(dtype), mask=rmask)


@libentry()
@triton.jit
def amin_split_kernel(
    x_ptr,
    mid_ptr,
    M,
    N,
    S,
    CHUNK,
    BLOCK: tl.constexpr,
):
    dtype = x_ptr.dtype.element_ty
    acc_type = tl.float32 if dtype is tl.bfloat16 else dtype
    pid_m = tl.program_id(0)
    pid_s = tl.program_id(1)
    start = pid_s * CHUNK
    end = tl.minimum(start + CHUNK, N)
    acc = tl.full([BLOCK], float("inf"), dtype=acc_type)
    for off in range(0, CHUNK, BLOCK):
        idx = start + off + tl.arange(0, BLOCK)
        val = tl.load(
            x_ptr + pid_m * N + idx, mask=idx < end, other=float("inf")
        )
        acc = tl.minimum(acc, val.to(acc_type))
    tl.store(
        mid_ptr + pid_m * S + pid_s,
        tl.min(acc, axis=0).to(mid_ptr.dtype.element_ty),
    )


@libentry()
@triton.jit
def amin_split_final_kernel(
    mid_ptr,
    out_ptr,
    M,
    S,
    BLOCK_M: tl.constexpr,
    BLOCK_S: tl.constexpr,
):
    dtype = mid_ptr.dtype.element_ty
    acc_type = tl.float32 if dtype is tl.bfloat16 else dtype
    pid = tl.program_id(0)
    rows = pid * BLOCK_M + tl.arange(0, BLOCK_M)
    rmask = rows < M
    cols = tl.arange(0, BLOCK_S)
    cmask = cols < S
    val = tl.load(
        mid_ptr + rows[:, None] * S + cols[None, :],
        mask=rmask[:, None] & cmask[None, :],
        other=float("inf"),
    )
    tl.store(
        out_ptr + rows,
        tl.min(val.to(acc_type), axis=1).to(out_ptr.dtype.element_ty),
        mask=rmask,
    )


@libentry()
@triton.jit
def amin_mid_kernel(
    x_ptr,
    out_ptr,
    K,
    I,
    BLOCK_I: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    dtype = x_ptr.dtype.element_ty
    acc_type = tl.float32 if dtype is tl.bfloat16 else dtype
    pid_o = tl.program_id(0)
    pid_i = tl.program_id(1)
    i = pid_i * BLOCK_I + tl.arange(0, BLOCK_I)
    imask = i < I
    base = pid_o * K * I
    acc = tl.full([BLOCK_K, BLOCK_I], float("inf"), dtype=acc_type)
    for k0 in range(0, K, BLOCK_K):
        k = k0 + tl.arange(0, BLOCK_K)
        kmask = k < K
        val = tl.load(
            x_ptr + base + k[:, None] * I + i[None, :],
            mask=kmask[:, None] & imask[None, :],
            other=float("inf"),
        )
        acc = tl.minimum(acc, val.to(acc_type))
    tl.store(
        out_ptr + pid_o * I + i,
        tl.min(acc, axis=0).to(out_ptr.dtype.element_ty),
        mask=imask,
    )


# ---------------------------------------------------------------------------
# Legacy fallback kernels (used for the all-reduce form and for multi-axis or
# non-contiguous reductions).
# ---------------------------------------------------------------------------


@libentry()
@triton.jit
def amin_kernel_1(
    inp,
    mid,
    M,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tle.program_id(0)

    offset = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    inp_ptrs = inp + offset
    mask = offset < M
    max_value = get_dtype_max(inp.type.element_ty)
    inp_val = tl.load(inp_ptrs, mask=mask, other=max_value)
    amin_val = tl.min(inp_val)
    mid_ptr = mid + pid
    tl.store(mid_ptr, amin_val)


@libentry()
@triton.jit
def amin_kernel_2(mid, out, mid_size, BLOCK_MID: tl.constexpr):
    offset = tl.arange(0, BLOCK_MID)
    mid_ptrs = mid + offset
    mask = offset < mid_size
    max_value = get_dtype_max(mid.type.element_ty)
    mid_val = tl.load(mid_ptrs, mask=mask, other=max_value)
    amin_val = tl.min(mid_val)
    tl.store(out, amin_val)


@libentry()
@libtuner(
    configs=runtime.get_tuned_config("naive_reduction"),
    key=["M", "N"],
)
@triton.jit
def amin_kernel(
    inp,
    out,
    M,
    N,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    dtype = inp.type.element_ty
    max_value = get_dtype_max(dtype)

    # Map the program id to the row of inp it should compute.
    pid = tle.program_id(0)
    rows = pid * BLOCK_M + tl.arange(0, BLOCK_M)[:, None]
    inp = inp + rows * N
    out = out + rows
    row_mask = rows < M

    acc_type = tl.float32 if dtype is tl.bfloat16 else dtype
    _all = tl.full([BLOCK_M, BLOCK_N], value=max_value, dtype=acc_type)
    for off in range(0, N, BLOCK_N):
        cols = off + tl.arange(0, BLOCK_N)[None, :]
        col_mask = cols < N
        mask = row_mask and col_mask
        a = tl.load(inp + cols, mask, other=max_value)
        _all = tl.minimum(_all, a)
    all = tl.min(_all, axis=1)[:, None]
    tl.store(out, all, row_mask)


# ---------------------------------------------------------------------------
# Host-side dispatch helpers
# ---------------------------------------------------------------------------


def _amin_last(mat, out_flat, M, N):
    """Reduce the (M, N) contiguous matrix over its last axis."""
    bn = min(triton.next_power_of_2(N), 2048)
    bm = max(1, 4096 // bn)
    bm = min(bm, max(1, triton.next_power_of_2(M)))

    # Very few rows with a wide reduction: split the reduction axis so that the
    # device is filled with independent programs, then combine the partials.
    if M <= 32 and N >= 65536:
        s = max(1, min(1024, triton.cdiv(N, 16384)))
        chunk = triton.cdiv(N, s)
        block = min(triton.next_power_of_2(chunk), 4096)
        mid = torch.empty((M * s,), dtype=mat.dtype, device=mat.device)
        amin_split_kernel[(M, s)](mat, mid, M, N, s, chunk, BLOCK=block)
        amin_split_final_kernel[(1,)](
            mid,
            out_flat,
            M,
            s,
            BLOCK_M=max(1, triton.next_power_of_2(M)),
            BLOCK_S=triton.next_power_of_2(s),
        )
        return

    if triton.cdiv(M, bm) > 65535:
        bm = triton.next_power_of_2(triton.cdiv(M, 65535))
        while bm * bn > 8192 and bn > 1:
            bn //= 2
    amin_last_kernel[(triton.cdiv(M, bm),)](mat, out_flat, M, N, BLOCK_M=bm, BLOCK_N=bn)


def _amin_mid(mat, out_flat, O, K, I):
    """Reduce the (O, K, I) contiguous block over its middle axis."""
    bi = min(triton.next_power_of_2(I), 1024)
    bk = min(256, max(1, 8192 // bi))
    gi = triton.cdiv(I, bi)

    # Keep every program's element span inside int32 and the launch grid inside
    # the device core-dim limit.
    max_o = max(1, (2**31 - 1) // max(1, K * I))
    chunk_o = min(65535, max_o)
    if chunk_o >= O:
        amin_mid_kernel[(O, gi)](mat, out_flat, K, I, BLOCK_I=bi, BLOCK_K=bk)
    else:
        for start in range(0, O, chunk_o):
            rows = min(chunk_o, O - start)
            amin_mid_kernel[(rows, gi)](
                mat.narrow(0, start, rows),
                out_flat.narrow(0, start * I, rows * I),
                K,
                I,
                BLOCK_I=bi,
                BLOCK_K=bk,
            )


def _amin_single_dim(inp, d, keepdim):
    shape = list(inp.shape)
    ndim = len(shape)
    K = shape[d]
    I = 1
    for ax in range(d + 1, ndim):
        I *= shape[ax]
    O = 1
    for ax in range(0, d):
        O *= shape[ax]

    out_shape = list(shape)
    out_shape[d] = 1
    out = torch.empty(out_shape, dtype=inp.dtype, device=inp.device)
    out_flat = out.view(-1)

    with torch_device_fn.device(inp.device):
        if I == 1:
            _amin_last(inp.view(O, K), out_flat, O, K)
        else:
            _amin_mid(inp.view(O, K, I), out_flat, O, K, I)

    if not keepdim:
        out = out.squeeze(d)
    return out


def amin(inp, dim=None, keepdim=False):
    logger.debug("GEMS AMIN")
    assert inp.dtype in (
        torch.float32,
        torch.float16,
        torch.bfloat16,
    ), "amin only supports float dtypes"
    if dim is None or len(dim) == 0:
        M = inp.numel()
        block_size = triton.next_power_of_2(math.ceil(math.sqrt(M)))
        mid_size = triton.cdiv(M, block_size)
        block_mid = triton.next_power_of_2(mid_size)
        dtype = inp.dtype
        mid = torch.empty((mid_size,), dtype=dtype, device=inp.device)
        if not keepdim:
            out = torch.empty([], dtype=dtype, device=inp.device)
        else:
            shape = list(inp.shape)
            for i in range(0, inp.dim()):
                shape[i] = 1
            out = torch.empty(shape, dtype=dtype, device=inp.device)
        with torch_device_fn.device(inp.device):
            amin_kernel_1[(mid_size, 1)](
                inp,
                mid,
                M,
                block_size,
            )
            amin_kernel_2[(1, 1)](
                mid, out, mid_size, block_mid
            )  # max block size is 128k, so mid does not requires int64 index
        return out

    dims = [d % inp.ndim for d in dim]
    if inp.is_contiguous() and len(set(dims)) == 1:
        return _amin_single_dim(inp, dims[0], keepdim)

    if isinstance(dim, int):
        dim = [dim]
    assert ((i >= -inp.ndim and i < inp.ndim) for i in dim), "Invalid dim"
    dtype = inp.dtype

    shape = list(inp.shape)
    dim = [d % inp.ndim for d in dim]
    inp = dim_compress(inp, dim)
    N = 1
    for i in dim:
        N *= shape[i]
        shape[i] = 1
    M = inp.numel() // N

    out = torch.empty(shape, dtype=dtype, device=inp.device)

    with torch_device_fn.device(inp.device):
        if M <= 65535:
            grid = lambda meta: (triton.cdiv(M, meta["BLOCK_M"]),)
            amin_kernel[grid](inp, out, M, N)
        else:
            # Ascend coreDim <= 65535；拆分行范围，原内核与调优配置不变。
            # 即使 autotune 选择 BLOCK_M=1，每次启动也不会超限。
            flat_input = inp.reshape(-1)
            flat_output = out.reshape(-1)
            for start in range(0, M, 65528):
                rows = min(65528, M - start)
                grid = lambda meta: (triton.cdiv(rows, meta["BLOCK_M"]),)
                amin_kernel[grid](flat_input[start * N:], flat_output[start:], rows, N)
    if not keepdim:
        out = out.squeeze(dim=dim)
    return out


def amin_(inp, dim=None, keepdim=False):
    logger.debug("GEMS AMIN_")
    assert inp.dtype in (
        torch.float32,
        torch.float16,
        torch.bfloat16,
    ), "amin_ only supports float dtypes"
    if isinstance(dim, int):
        dim = [dim]
    if dim is None or len(dim) == 0:
        M = inp.numel()
        block_size = triton.next_power_of_2(math.ceil(math.sqrt(M)))
        mid_size = triton.cdiv(M, block_size)
        block_mid = triton.next_power_of_2(mid_size)
        dtype = inp.dtype
        mid = torch.empty((mid_size,), dtype=dtype, device=inp.device)
        if not keepdim:
            out = torch.empty([], dtype=dtype, device=inp.device)
        else:
            shape = list(inp.shape)
            for i in range(0, inp.dim()):
                shape[i] = 1
            out = torch.empty(shape, dtype=dtype, device=inp.device)
        with torch_device_fn.device(inp.device):
            amin_kernel_1[(mid_size, 1)](
                inp,
                mid,
                M,
                block_size,
            )
            amin_kernel_2[(1, 1)](mid, out, mid_size, block_mid)
        inp.copy_(out.reshape(inp.shape) if keepdim else out)
        return inp
    else:
        result = amin(inp, dim=dim, keepdim=True)
        inp.copy_(result)
        return inp


_master_amin = amin
def run(inp, dim=None, keepdim=False):
    if isinstance(dim, int):
        dim = [dim]
    return _master_amin(inp, dim=dim, keepdim=keepdim)

# KGS 要求公开符号与 run 为同一个入口；原内核保持不变。
amin = run
