# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
#
# amin: min over `dim` of a contiguous float tensor.
#
# Layout view used here: with r = min(dim) and s = max(dim),
#   S_out = prod(shape[:r]),  K = prod(shape[r:s+1]),  S_in = prod(shape[s+1:])
#   addr(o, k, i) = (o * K + k) * S_in + i
# so the reduced axis is a middle axis in general (K), the trailing axis S_in
# indexes the output contiguously and the leading axis S_out is the rest of the
# output.  Two tile shapes follow from that:
#   S_in > 1 -> tile [BK, BN] (BN over the contiguous output axis) with an
#               element-wise accumulate; only the final min over BK is crossed.
#   S_in == 1 -> tile [BM, BN] (BN over the contiguous reduced axis); the final
#               min over BN is crossed once per tile.
# Reducing dims that do not form one contiguous range is done by reducing each
# maximal contiguous range in turn (min is associative), which keeps the same
# kernels valid and never needs a permute/contiguous copy.
# A full reduction (|dims| == ndim) is a single atomic-min kernel.

import torch
import triton
import triton.language as tl

_MAXV = {
    torch.float16: 65504.0,
    torch.bfloat16: 3.3895313892515355e38,
    torch.float32: 3.4028234663852886e38,
}


@triton.jit
def _flat_atomic(inp, out, M, GRIDX, BS: tl.constexpr, ACC: tl.constexpr, OTHER: tl.constexpr):
    pid = tl.program_id(0) + tl.program_id(1) * GRIDX
    off = pid * BS + tl.arange(0, BS)
    v = tl.load(inp + off, mask=off < M, other=OTHER)
    if ACC:
        tl.atomic_min(out, tl.min(v.to(tl.float32), axis=0).to(out.dtype.element_ty))
    else:
        tl.atomic_min(out, tl.min(v, axis=0))


@triton.jit
def _row_even(inp, out, R, K, GRIDX, BM: tl.constexpr, BN: tl.constexpr, ACC: tl.constexpr):
    pid = tl.program_id(0) + tl.program_id(1) * GRIDX
    r = pid * BM + tl.arange(0, BM)
    base = inp + r[:, None] * K
    k = tl.arange(0, BN)[None, :]
    x = tl.load(base + k)
    acc = x.to(tl.float32) if ACC else x
    for k0 in range(BN, K, BN):
        y = tl.load(base + (k0 + k))
        acc = tl.minimum(acc, y.to(tl.float32) if ACC else y)
    tl.store(out + r, tl.min(acc, axis=1).to(out.dtype.element_ty))


@triton.jit
def _row_mask(inp, out, R, K, GRIDX, BM: tl.constexpr, BN: tl.constexpr, ACC: tl.constexpr, OTHER: tl.constexpr):
    pid = tl.program_id(0) + tl.program_id(1) * GRIDX
    r = pid * BM + tl.arange(0, BM)
    rm = r < R
    base = inp + r[:, None] * K
    acc = (tl.full([BM, BN], OTHER, dtype=tl.float32) if ACC
           else tl.full([BM, BN], OTHER, dtype=inp.dtype.element_ty))
    for k0 in range(0, K, BN):
        k = k0 + tl.arange(0, BN)[None, :]
        y = tl.load(base + k, mask=rm[:, None] & (k < K), other=OTHER)
        acc = tl.minimum(acc, y.to(tl.float32) if ACC else y)
    tl.store(out + r, tl.min(acc, axis=1).to(out.dtype.element_ty), rm)


@triton.jit
def _col_even(inp, out, S_out, K, S_in, GRIDX, BN: tl.constexpr, BK: tl.constexpr, ACC: tl.constexpr):
    pid = tl.program_id(0) + tl.program_id(1) * GRIDX
    nbn = tl.cdiv(S_in, BN)
    o = pid // nbn
    i = (pid % nbn) * BN + tl.arange(0, BN)
    base = inp + o * K * S_in + i
    k = tl.arange(0, BK)[:, None]
    x = tl.load(base[None, :] + k * S_in)
    acc = x.to(tl.float32) if ACC else x
    for k0 in range(BK, K, BK):
        y = tl.load(base[None, :] + (k0 + k) * S_in)
        acc = tl.minimum(acc, y.to(tl.float32) if ACC else y)
    tl.store(out + o * S_in + i, tl.min(acc, axis=0).to(out.dtype.element_ty))


@triton.jit
def _col_mask(inp, out, S_out, K, S_in, GRIDX, BN: tl.constexpr, BK: tl.constexpr, ACC: tl.constexpr, OTHER: tl.constexpr):
    pid = tl.program_id(0) + tl.program_id(1) * GRIDX
    nbn = tl.cdiv(S_in, BN)
    o = pid // nbn
    i = (pid % nbn) * BN + tl.arange(0, BN)
    im = i < S_in
    base = inp + o * K * S_in + i
    acc = (tl.full([BK, BN], OTHER, dtype=tl.float32) if ACC
           else tl.full([BK, BN], OTHER, dtype=inp.dtype.element_ty))
    for k0 in range(0, K, BK):
        k = k0 + tl.arange(0, BK)[:, None]
        y = tl.load(base[None, :] + k * S_in, mask=im[None, :] & (k < K), other=OTHER)
        acc = tl.minimum(acc, y.to(tl.float32) if ACC else y)
    tl.store(out + o * S_in + i, tl.min(acc, axis=0).to(out.dtype.element_ty), im)


def _grid2d(n):
    gx = n if n <= 65535 else 65535
    return gx, triton.cdiv(n, gx)


def _row_cfg(R, K, esize):
    """[BM, BN] tile over a contiguous reduced axis (S_in == 1)."""
    BM, BN_des = (4, 1024) if esize == 4 else (8, 512)
    BN = min(BN_des, triton.next_power_of_2(K))
    if R < BM:
        BM = triton.next_power_of_2(R)
    return BM, BN, (R % BM == 0) and (K % BN == 0)


def _col_cfg(S_in, K, esize):
    """[BK, BN] tile over a contiguous output axis (S_in > 1)."""
    BN_des, BK_des = (256, 16) if esize == 4 else (512, 16)
    BN = min(BN_des, triton.next_power_of_2(S_in))
    BK = BK_des
    while BK > 1 and K % BK:
        BK //= 2
    return BN, BK, (S_in % BN == 0) and (K % BK == 0)


def _reduce_range(t, a, b, dst, esize):
    """Min over dims [a, b] (one contiguous range) of contiguous tensor t."""
    shp = t.shape
    S_out = 1
    for s in shp[:a]:
        S_out *= s
    K = 1
    for s in shp[a:b + 1]:
        K *= s
    S_in = 1
    for s in shp[b + 1:]:
        S_in *= s
    acc32 = t.dtype == torch.bfloat16
    if S_in > 1:
        BN, BK, even = _col_cfg(S_in, K, esize)
        gx, gy = _grid2d(S_out * triton.cdiv(S_in, BN))
        if even:
            _col_even[(gx, gy)](t, dst, S_out, K, S_in, gx, BN=BN, BK=BK, ACC=acc32)
        else:
            _col_mask[(gx, gy)](t, dst, S_out, K, S_in, gx, BN=BN, BK=BK, ACC=acc32,
                                OTHER=_MAXV[t.dtype])
    else:
        BM, BN, even = _row_cfg(S_out, K, esize)
        gx, gy = _grid2d(triton.cdiv(S_out, BM))
        if even:
            _row_even[(gx, gy)](t, dst, S_out, K, gx, BM=BM, BN=BN, ACC=acc32)
        else:
            _row_mask[(gx, gy)](t, dst, S_out, K, gx, BM=BM, BN=BN, ACC=acc32,
                                OTHER=_MAXV[t.dtype])


def run(inp, dim=None, keepdim=False):
    assert inp.dtype in (
        torch.float16,
        torch.float32,
        torch.bfloat16,
    ), "amin only supports float dtypes"
    if isinstance(dim, int):
        dim = [dim]
    nd = inp.dim()
    if dim is None or len(dim) == 0:
        dims = list(range(nd))
    else:
        dims = sorted({int(d) % nd for d in dim})
    esize = inp.element_size()
    dt = inp.dtype
    shape = inp.shape
    out_shape = list(shape)
    for d in dims:
        out_shape[d] = 1

    if len(dims) == nd:
        # single fully reduced value: one atomic-min kernel
        M = inp.numel()
        out = torch.full(out_shape, _MAXV[dt], dtype=dt, device=inp.device)
        dst = out.reshape(-1)
        BS = 4096 if M % 4096 == 0 else (2048 if M % 2048 == 0 else 1024)
        gx, gy = _grid2d(triton.cdiv(M, BS))
        _flat_atomic[(gx, gy)](inp, dst, M, gx, BS=BS, ACC=(dt == torch.bfloat16),
                               OTHER=_MAXV[dt])
    else:
        ranges = []
        start = prev = dims[0]
        for d in dims[1:]:
            if d == prev + 1:
                prev = d
            else:
                ranges.append((start, prev))
                start = prev = d
        ranges.append((start, prev))
        out = torch.empty(out_shape, dtype=dt, device=inp.device)
        t = inp
        last = len(ranges) - 1
        for idx, (a, b) in enumerate(ranges):
            if idx == last:
                dst = out.reshape(-1)
            else:
                mshape = list(t.shape)
                for d in range(a, b + 1):
                    mshape[d] = 1
                mid = torch.empty(mshape, dtype=dt, device=inp.device)
                dst = mid.reshape(-1)
            _reduce_range(t, a, b, dst, esize)
            if idx != last:
                t = mid
    if not keepdim:
        out = out.squeeze(dim=dims)
    return out


amin = run
