# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
"""Triton implementation of ``torch.narrow_copy(inp, dim, start, length)``.

For a plain row-major input the narrowed slab is ``pre = prod(shape[:dim])``
contiguous runs of ``chunk = length * prod(shape[dim+1:])`` elements and the
result is a freshly allocated contiguous tensor, so the operator is a pure block
copy:

    out[r * chunk + i] = inp[r * dim_size * post + start * post + i]

The previous candidate mapped every flat output index through two integer
divisions plus a modulo by *runtime* divisors.  Integer division on this target
is bit-serial and costs roughly 14 us of device time per 1024-element program,
so the kernel was ALU-bound at ~1.4 Gelem/s instead of bandwidth-bound; it also
split large launches into 8192-program slices, paying one extra kernel per
8.4M elements.  This implementation never divides per element:

* ``pre == 1`` -- the slab is one contiguous block, so the kernel walks a flat
  range with only a per-program block index.
* ``pre > 1`` -- one tile covers a BLOCK-sized piece of one run; the run index is
  derived once per tile with a single scalar division and each run is itself
  contiguous, so again there is no per-element index arithmetic.

Both use a grid-striding ``tl.range`` loop whose program count is capped by the
device's vector-core count, queried at runtime and never hard-coded, so each
program keeps a deep pipelined copy loop.
"""

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)

# Element count at or below which a single program copies the whole slab.
_SINGLE_PROGRAM_ELEMS = 4096
# Element count at or below which a 4K tile is used instead of a 16K tile.
_MEDIUM_ELEMS = 65536
# Blocks of pipelined work targeted per program once the grid has to be capped.
_BLOCKS_PER_PROGRAM = 12
# Conservative cap used only when the vector-core count cannot be queried.
_FALLBACK_PROGRAM_CAP = 256
_MIN_BLOCK = 16

_VECTOR_CORES = None
_CORES_PROBED = False


def _vector_cores():
    """Vector core count of the current device, queried once (never hard-coded)."""
    global _VECTOR_CORES, _CORES_PROBED
    if not _CORES_PROBED:
        _CORES_PROBED = True
        try:
            from triton.runtime import driver as _driver

            props = _driver.active.utils.get_device_properties(
                torch.npu.current_device()
            )
            for key in ("num_vectorcore", "num_aicore"):
                value = None
                try:
                    value = props[key]
                except Exception:
                    value = getattr(props, key, None)
                if value:
                    _VECTOR_CORES = int(value)
                    break
        except Exception:  # pragma: no cover - property query is best effort
            _VECTOR_CORES = None
    return _VECTOR_CORES


@triton.jit
def narrow_copy_flat_kernel(
    out_ptr,
    inp_ptr,
    base_in,
    n_elements,
    nblocks,
    BLOCK_SIZE: tl.constexpr,
    EVEN: tl.constexpr,
):
    """Copy one contiguous run of ``n_elements`` starting at ``base_in``."""
    grid = tl.num_programs(0)
    for block in tl.range(tl.program_id(0), nblocks, grid):
        offsets = block * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
        if EVEN:
            tl.store(out_ptr + offsets, tl.load(inp_ptr + base_in + offsets))
        else:
            mask = offsets < n_elements
            tl.store(
                out_ptr + offsets,
                tl.load(inp_ptr + base_in + offsets, mask=mask),
                mask=mask,
            )


@triton.jit
def narrow_copy_runs_kernel(
    out_ptr,
    inp_ptr,
    base_in,
    chunk,
    src_stride,
    nblocks_per_run,
    ntiles,
    BLOCK_SIZE: tl.constexpr,
    EVEN: tl.constexpr,
):
    """Copy ``ntiles`` BLOCK-sized tiles of ``pre`` contiguous runs of ``chunk``."""
    grid = tl.num_programs(0)
    for tile in tl.range(tl.program_id(0), ntiles, grid):
        run = tile // nblocks_per_run
        block = tile - run * nblocks_per_run
        offsets = block * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
        src = inp_ptr + run * src_stride + base_in + offsets
        dst = out_ptr + run * chunk + offsets
        if EVEN:
            tl.store(dst, tl.load(src))
        else:
            mask = offsets < chunk
            tl.store(dst, tl.load(src, mask=mask), mask=mask)


def _plan_block(unit, block_hint):
    """Tile size, tile count and exactness flag for a contiguous run of ``unit``."""
    if unit <= _SINGLE_PROGRAM_ELEMS:
        block = triton.next_power_of_2(unit)
        if block < _MIN_BLOCK:
            block = _MIN_BLOCK
        elif block > _SINGLE_PROGRAM_ELEMS:
            block = _SINGLE_PROGRAM_ELEMS
    elif unit <= _MEDIUM_ELEMS:
        block = 4096
    else:
        block = 16384
    if block_hint and block > block_hint:
        block = block_hint
    n_blocks = (unit + block - 1) // block
    even = (unit % block) == 0
    return block, n_blocks, even


def _grid_for(n_blocks):
    """Program count: one program per block when they fit, else core-sized."""
    cores = _vector_cores()
    cap = cores if cores else _FALLBACK_PROGRAM_CAP
    if n_blocks <= cap:
        return n_blocks
    grid = n_blocks // _BLOCKS_PER_PROGRAM
    if grid < cap:
        grid = cap
    if grid > n_blocks:
        grid = n_blocks
    return grid


def narrow_copy(inp, dim, start, length):
    logger.debug("GEMS NARROW_COPY")
    assert (
        dim >= -inp.ndim and dim < inp.ndim
    ), f"Invalid dim: {dim} for tensor with {inp.ndim} dimensions"
    dim = dim % inp.ndim

    # Handle negative start
    if start < 0:
        start = start % inp.size(dim)

    # Clamp length to valid range
    length = min(length, inp.size(dim) - start)

    # Compute output shape
    out_shape = list(inp.shape)
    out_shape[dim] = length
    out = torch.empty(out_shape, dtype=inp.dtype, device=inp.device)

    if out.numel() == 0:
        return out

    # Make input contiguous for simpler indexing
    inp = inp.contiguous()

    dim_size = inp.size(dim)
    post = 1
    for d in range(dim + 1, inp.ndim):
        post *= inp.size(d)

    n_total = out.numel()
    chunk = length * post
    pre = n_total // chunk
    base_in = start * post

    if pre == 1:
        # Single contiguous slab: out[i] = inp[base_in + i]
        block, n_blocks, even = _plan_block(n_total, 0)
        narrow_copy_flat_kernel[(_grid_for(n_blocks),)](
            out,
            inp,
            base_in,
            n_total,
            n_blocks,
            BLOCK_SIZE=block,
            EVEN=even,
        )
    else:
        # `pre` contiguous runs of `chunk` elements, source stride dim_size * post
        block, n_blocks, even = _plan_block(chunk, 4096)
        narrow_copy_runs_kernel[(_grid_for(pre * n_blocks),)](
            out,
            inp,
            base_in,
            chunk,
            dim_size * post,
            n_blocks,
            pre * n_blocks,
            BLOCK_SIZE=block,
            EVEN=even,
        )

    return out


run = narrow_copy
