"""Public request, response, and client protocol."""

from .version import (
    ApiVersion,
    KERNELGEN_API_VERSION,
    KERNELGEN_SERVER_VERSION,
    KERNELGEN_SUPPORTED_API_VERSIONS,
)
from .schema import (
    AdapterCapabilities,
    AdapterCase,
    AdapterManifest,
    BoundEvaluateRequest,
    CandidateContract,
    CaseList,
    CorrectnessResult,
    Definition,
    EvaluateRequest,
    EvaluateResponse,
    EvaluationSettings,
    EvaluationStatus,
    EvaluatorBinding,
    Implementation,
    InspectRequest,
    Language,
    PreflightResult,
    ReferenceDevice,
    SourceFile,
    TimingResult,
    Tolerance,
    Workload,
    WorkloadResult,
    WorkloadStatus,
)

__all__ = [
    "AdapterCapabilities",
    "AdapterCase",
    "AdapterManifest",
    "BoundEvaluateRequest",
    "CandidateContract",
    "CaseList",
    "CorrectnessResult",
    "Definition",
    "EvaluateRequest",
    "EvaluateResponse",
    "EvaluationSettings",
    "EvaluationStatus",
    "EvaluatorBinding",
    "Implementation",
    "InspectRequest",
    "Language",
    "PreflightResult",
    "ReferenceDevice",
    "SourceFile",
    "TimingResult",
    "Tolerance",
    "Workload",
    "WorkloadResult",
    "WorkloadStatus",
    "ApiVersion",
    "KERNELGEN_API_VERSION",
    "KERNELGEN_SERVER_VERSION",
    "KERNELGEN_SUPPORTED_API_VERSIONS",
]
